nordpool-out.ttl: nordpool-simple.ttl ../Ontology/ruleless-digital-twins.ttl inference-rules.rules
	java -jar ruleless-digital-twins-inference-engine.jar ../Ontology/ruleless-digital-twins.ttl nordpool-simple.ttl inference-rules.rules nordpool-out.ttl
