import typing
from rdflib import BNode, Literal, Graph, URIRef
from rdflib.namespace import Namespace, RDF, RDFS, OWL, XSD
from RDTBindings import *

g = Graph()
MINE = Namespace("http://www.semanticweb.org/vs/ontologies/2025/11/untitled-ontology-97#")

# g.add((BNode(), RDFS["annotation"], Literal("Generated by SimpleNordpool.py", datatype=XSD.string)))
g.add((URIRef(str(MINE)), OWL.imports, URIRef(str(RDT))))

# Not needed since we now have the zone:
# dummyProperty = ObservableProperty(g, MINE["DummyProperty"], RestrictionL1D(g))
# change = Change(g, MINE["DummyChange"], dummyProperty)
# dummyActuator = Actuator(g, MINE["UnitActuator"], change)
# g.add((dummyActuator.node, RDT["hasActuatorState"], Literal("0", datatype=XSD.integer))) # XXX

zoneProperty = ObservableProperty(g, MINE["zone"])
zoneChange = Change(g, MINE["ZoneChange"], zoneProperty)
zoneActuator = Actuator(g, MINE["ZoneActuator"], zoneChange)
# Only add the zone you want for now:
g.add((zoneActuator.node, RDT["hasActuatorState"], Literal("NO1", datatype=XSD.string)))
# g.add((zoneActuator.node, RDT["hasActuatorState"], Literal("NO5", datatype=XSD.string)))

roomO = Platform(g, MINE["Test"], False, [zoneActuator])
fmuO = FMU(g, MINE["TestFMU"], "NordPool.fmu", 900) # 15 mins
roomO.addFMU(g, fmuO)

elprice = ObservableProperty(g, MINE["price"])
restriction = elprice.restriction

elpriceNFO = ObservableProperty(g, MINE["notFound"], restriction) # TODO: better implicit sharing?

priceMeasure = Measure(g, MINE["PriceMeasure"], restriction)
priceSensor = Sensor(g, MINE["PriceSensor"], [elprice, elpriceNFO])

priceProcedureO = Procedure(g, MINE["PriceProcedure"], priceMeasure, priceSensor)

dummyMeasure = Measure(g, MINE["DummyMeasure"], restriction)
dummyProcedure = Procedure(g, MINE["DummyProcedure"], dummyMeasure)
dummyProperty = ObservableProperty(g, MINE["DummyProperty"], restriction)
dummySensor = Sensor(g, MINE["DummySensor"], dummyProperty)

output = g.serialize(destination=None)
print(output)