import typing
from rdflib import BNode, Literal, Graph, URIRef
from rdflib.namespace import Namespace, RDF, RDFS, OWL, XSD
from RDTBindings import *

g = Graph()
MINE = Namespace("http://www.semanticweb.org/vs/ontologies/2025/11/untitled-ontology-97#")

# g.add((BNode(), RDFS["annotation"], Literal("Generated by Incubator.py", datatype=XSD.string)))
g.add((URIRef(str(MINE)), OWL.imports, URIRef(str(RDT))))

zoneProperty = ObservableProperty(g, MINE["ZoneProperty"])
zoneChange = Change(g, MINE["ZoneChange"], zoneProperty)
zoneActuator = Actuator(g, MINE["ZoneActuator"], zoneChange, isParameter=True,
                            actuatorName="zone", actuatorStates=["NO1"], actuatorType=XSD.string)
# Only add the zone you want for now:
# g.add((zoneActuator.node, RDT["hasActuatorState"], Literal("NO5", datatype=XSD.string)))

elprice = ObservableProperty(g, MINE["price"])
elpriceNF = ObservableProperty(g, MINE["notFound"])

priceMeasure = Measure(g, MINE["PriceMeasure"])
priceSensor = Sensor(g, MINE["PriceSensor"], [elprice, elpriceNF])
priceProcedureO = Procedure(g, MINE["PriceProcedure"], priceMeasure, priceSensor)

roomO = Platform(g, MINE["Test"], False, [zoneActuator, priceSensor])
fmuO = FMU(g, MINE["TestFMU"], "NordPool.fmu", 900) # 15 mins
roomO.addFMU(g, fmuO)

output = g.serialize(destination=None)
print(output)
